version: '3.9'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    networks:
      default:
        aliases:
          - minio
  console:
    image: minio/console
    ports:
      - "9001:9090"
    environment:
      CONSOLE_MINIO_SERVER: http://minio:9000
      CONSOLE_MINIO_SERVER_TLS_SKIP_VERIFICATION: "true"
      CONSOLE_PBKDF_ROUNDS: "100000"
      CONSOLE_PBKDF_PASSPHRASE: minio123
      CONSOLE_ROOT_USER: minio
      CONSOLE_ROOT_PASSWORD: minio123
    command: server
    depends_on:
      - minio
    networks:
      default:
        aliases:
          - console
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raw_metadata
    networks:
      default:
        aliases:
          - db
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@db.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - pgadmin
  tools:
    build: ./tools
    volumes:
      - ./shared:/app/shared # Replace the shared_volume volume with a host directory
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      default:
        aliases:
          - rabbitmq
  harvest_worker:
    build:
      context: ./harvest
      dockerfile: Dockerfile.worker
    depends_on:
      - minio
      - postgres
      - tools
      - rabbitmq
    environment:
      SQL_HOST: db
      SQL_USER: bigdatauser
      SQL_PASSWORD: bigdatapassword
      SQL_DATABASE: bigdata
      SQL_PORT: 3306
    volumes:
      - ./shared:/app/shared
    networks:
      default:
        aliases:
          - harvest_worker
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - milvus_etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
  miniomilvus:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - milvus_minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.5
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: miniomilvus:9000
    volumes:
      - milvus_data:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    restart: always
  milvus-insight:
    image: milvusdb/milvus-insight
    ports:
      - "3000:3000"
    environment:
      MILVUS_ADDRESS: standalone:19530
    networks:
      default:
        aliases:
          - milvus-insight
  gateway:
    build: ./gateway
    ports:
      - "81:80"
    depends_on:
      - gather
      - harvest
      - tools
      - minio
      - postgres
    volumes:
      - ./shared:/app/shared # Replace the shared_volume volume with a host directory
    environment:
      GATHER_SERVICE_URL: http://gather:4001/
      HARVEST_SERVICE_URL: http://harvest:4002/
      VISUALIZE_SERVICE_URL: http://visualize:4003/
      RECOMMEND_SERVICE_URL: http://recommend:4004/
      CDN_SERVICE_URL: http://cdn:4006/
    networks:
      default:
        aliases:
          - gateway
  gather:
    build: ./gather
    depends_on:
      - tools
      - minio
      - postgres
    environment:
      # TODO: Change the ENV var for each service to match cause theree is update in the code
      SQL_HOST: db
      SQL_USER: bigdatauser
      SQL_PASSWORD: bigdatapassword
      SQL_DATABASE: bigdata
      SQL_PORT: 3306
    volumes:
      - ./shared:/app/shared # Replace the shared_volume volume with a host directory
    networks:
      default:
        aliases:
          - gather
  recommend:
    build: ./recommend
    depends_on:
      - tools
      - minio
      - postgres
      - standalone
      - milvus-insight
      - rabbitmq
      - harvest_worker
      - preprocess
      - gather
      - visualize
      - gateway
      - harvest
    networks:
      default:
        aliases:
          - recommend
  harvest:
    build: ./harvest
    depends_on:
      - minio
      - postgres
      - tools
    environment:
      SQL_HOST: db
      SQL_USER: bigdatauser
      SQL_PASSWORD: bigdatapassword
      SQL_DATABASE: bigdata
      SQL_PORT: 3306
    volumes:
      - ./shared:/app/shared # Replace the shared_volume volume with a host directory
    networks:
      default:
        aliases:
          - harvest
  preprocess:
    build: ./preprocess
    depends_on:
      - minio
      - postgres
      - standalone
      - tools
    environment:
      SQL_HOST: db
      SQL_USER: bigdatauser
      SQL_PASSWORD: bigdatapassword
      SQL_DATABASE: bigdata
      SQL_PORT: 3306
    volumes:
      - ./shared:/app/shared # Replace the shared_volume volume with a host directory
    networks:
      default:
        aliases:
          - preprocess
  visualize:
    build: ./visualize
    depends_on:
      - minio
      - postgres
      - standalone
      - tools
    networks:
      default:
        aliases:
          - visualize
  client:
    build: ./client
    depends_on:
      - gateway
      - gather
      - harvest
      - tools
      - minio
      - postgres
      - standalone
      - milvus-insight
      - rabbitmq
      - harvest_worker
      - preprocess
      - visualize
      - recommend
    ports:
      - "4005:4005"
    networks:
      default:
        aliases:
          - client

  cdn:
    build: ./cdn
    depends_on:
      - gateway
      - gather
      - harvest
      - tools
      - minio
      - postgres
      - standalone
      - milvus-insight
      - rabbitmq
      - harvest_worker
      - preprocess
      - visualize
      - recommend
    ports:
      - "4006:4006"
    networks:
      default:
        aliases:
          - cdn

volumes:
  pg_data:
  milvus_data:
  milvus_etcd:
  milvus_minio:

networks:
  default:
    name: bigdata
